replicaCount: 1

image:
  repository: us-east1-docker.pkg.dev/cinemates-497209/cinemates-frontend/frontend
  pullPolicy: IfNotPresent
  # Defaults to .Chart.AppVersion when left empty.
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

containerPorts:
  - name: http
    containerPort: 80
    protocol: TCP

# nginx serves index.html at "/",  an HTTP probe is appropriate here.
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

service:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
