name: CI Pipeline for Backend

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/**'
      - 'helm-charts/**'
    branches:
      - main
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/**'
      - 'helm-charts/**'
    branches:
      - main
  workflow_dispatch:


env:
  DATABASE_URL: ${{ secrets.DB_URL }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  API_KEY: ${{ secrets.API_KEY }}

# url: https://github.com/marketplace/actions/push-to-gcr-github-action
#  Build and push Docker image to Artifact Registry
jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    outputs:
      image_tag: ${{ steps.set-image-tag.outputs.image_tag }}

    steps:
      - uses: actions/checkout@v5

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      # Extract metadata for the Docker image tags
      - name: Extract metadata
        id: vars
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF##*/}" | tr '/' '-')
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-8)
          IMAGE_TAG="${BRANCH_NAME}-${SHORT_SHA}-${{ github.run_number }}"

          echo "branch=${BRANCH_NAME}" >> $GITHUB_OUTPUT
          echo "sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-east1-docker.pkg.dev --quiet

      - uses: RafikFarhad/push-to-gcr-github-action@v5
        with:
          registry: us-east1-docker.pkg.dev
          project_id: cinemates-497209
          image_name: cinemates-backend/backend
          image_tag: latest,${{ steps.vars.outputs.tag }}
          dockerfile: backend/Dockerfile
          context: .

    